
# About the project

<!-- *Write a short description about the course and add a link to your GitHub repository here. This is an R Markdown (.Rmd) file so you should use R Markdown syntax.* -->

Introduction to Open Data Science.
From October to December 2020, learning the basics of open data, R, RMarkdown and GitHub.
I discovered this course on out University Yammer feed. Since it contains a lot of subjects I've been meaning to delve into, it was a no-brainer to enrol.
Looking forward to play around in RStudio and strengthen my knowledge in statistical computing!

Find my course repository at
[github.com/CGBoing/IODS-project](https://github.com/CGBoing/IODS-project)

***

# Exercise 1

<!-- *Describe the work you have done this week and summarize your learning.* -->

Getting acquainted with RMarkdown and GitHub.
I've used Azure Repos with Git before, so I'm confident I'll be getting up to speed quickly.
R has quite interesting syntax. MATLAB is more familiar to me via my line of work.

<!-- - Describe your work and results clearly.  -->
<!-- - Assume the reader has an introductory course level understanding of writing and reading R code as well as statistical methods. -->
<!-- - Assume the reader has no previous knowledge of your data or the more advanced methods you are using. -->

Learning some useful key commands. What might be the fastest way from my keyboard to GitHub. Maybe I'll formulate some ideas for scripts.
It's not just an obsession with speed -- trying out things in quick succession is efficient learning tactic.

## RMarkdown playground

Here I am testing what RMarkdown offers.

### Highlighting

Here's some **bold text**, or would you like it _italic_?
Didn't find underlining though, so let's just ~~strike it through~~.
Maybe go nuts with some ^superscripting^?

### Lists

* I am a bullet point.
* Me too!

### Links

[Thurrott.com - The Home for Tech Enthusiasts: News, Reviews & Analysis](https://www.thurrott.com)  
[Precipitation in Finland](https://en.ilmatieteenlaitos.fi/rain-and-cloudiness)  
[Official R documentation](https://cran.r-project.org/doc/manuals/r-release/R-intro.html)  

### Code

```{r}

c(1:5)
str(c)

```
